version: "3.7"
services:

  app:
    build: .
    expose:
      - "8765"
    ports:
      - "8765:8765"
    environment:
      PORT: 8765
      MONGOURI: 'mongodb+srv://dbTestuser:<password>@cluster0-zc3ak.mongodb.net/test?retryWrites=true&w=majority'
      GOOGLEID: 175845741268-gn6j8jrlguee95o6qurdea7m2fmgmobi.apps.googleusercontent.com
      GOOGLESECRET: mIjngOK5nH5I7bIEANdlmcMA
